yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),    
    path('posts/<post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<comment_id>/comment_delete/', views.comment_delete, name='comment_delete'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view
        (template_name='users/login.html'),
        name='login'),
    path(
        'logout/',
        LogoutView.as_view
        (template_name='users/logged_out.html'),
        name='logout'),
    path(
        'password_change/',
        LoginView.as_view
        (template_name='users/password_change_form.html'),
        name='password_change'),
    path(
        'password_change/done/',
        LoginView.as_view
        (template_name='users/password_change_done.html'),
        name='password_change_done'),
    path(
        'password_reset/',
        PasswordResetView.as_view
        (template_name='users/password_reset_form.html'),
        name='password_reset'),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view
        (template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view
        (template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset/done/',
        LoginView.as_view
        (template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

yatube/templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% else %}
    <h6 style="background-color: FireBrick; width: 500px; color: yellow">Комментируют только зарегистрированный пользователи</h6>
{% endif %}


{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <li class="list-group-item">
          <p>
           {{ comment.text }}
          </p>        
           {{ comment.created|date:"d.m.Y H:i" }}           
        </li> 
        {% if comment.author == request.user %}          
          <a class="btn btn-sm btn-secondary rounded" href="{% url 'posts:comment_delete' comment.pk %}" role="button"> 
            Удалить пост
          </a>
        {% endif %}
      </div>
    </div>
{% endfor %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
    {% load static %}
      <header>      
        <nav class="navbar navbar-light" style="background-color: lightskyblue">
          <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
              <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
              <span style="color:red">Ya</span>tube
            </a>            
            {% with request.resolver_match.view_name as view_name %}
            <ul class="nav nav-pills">
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
                  href="{% url 'about:author' %}">Об авторе</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
                 href="{% url 'about:tech' %}">Технологии</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
                 href="{% url 'posts:post_create' %}">Новая запись</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link link-light" href="{% url 'password_change' %}">Изменить пароль</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
              </li>
              <li>
                Пользователь: {{ user.username }}
              <li>
              {% else %}
              <li class="nav-item"> 
                <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
              </li>
              {% endif %}
            </ul>
            {% endwith %}
          </div>
        </nav>     
        <h1>{% block header %}{{ group.title }}{% endblock %}</h1>
      </header>

yatube/templates/includes/style.html
{% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}> 